# Generated by Django 2.1.1 on 2018-10-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181002_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='id',
        ),
        migrations.RemoveField(
            model_name='university',
            name='id',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
